# Generated by Django 4.1.5 on 2023-01-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0004_arrival_coupon_coupon_type_customer_faqs_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories'),
        ),
    ]
